### ISSUE TITLE
Repository containing malicious files

### ISSUE THREAD

**Issue by flipp33r** [cjthimm/SuperMario-FR-#1]
Hi,
I hate to be a bearer of bad news, but it looks like this repository contains malware that you are likely not aware of.
Please treat this as a friendly notification. I suggest you to investigate origin of the below-mentioned file(s) and assume all systems involved in building or running your NetBeans project(s) to be fully compromised. I also suggest you to review all your other repositories and NetBeans projects for presence of similar files.

Suspicious file(s):

- https://github.com/cjthimm/SuperMario-FR-/blob/master/SuperMario(FR)/nbproject/cache.dat - This is a malicious file intended to install additional malware on a system and/or modify NetBeans projects (see VirusTotal: https://www.virustotal.com/gui/file/13e1f2716a0827b3f8933069319e08d07ea2b949141151a639dd2aef10d81985/detection)
- https://github.com/cjthimm/SuperMario-FR-/blob/master/SuperMario(FR)/nbproject/build-impl.xml#L922 - This is a modified `build-impl.xml` file intended to run malicious JAR file `cache.dat` every time a project is build

Cheers,
Flipper

**Comment by cjthimm** [comment]
This issue has been deemed to be spam. The user reporting the issue has an account that is only 2 days old at the time. They have reported the exact same issue with the exact same wording on 11 other gitHub projects. This is believed to be spam
![Annotation 2020-05-08 133125](https://user-images.githubusercontent.com/16627589/81437238-7411c200-9130-11ea-9815-bed606a21c73.png)
![Annotation 2020-05-08 1331251](https://user-images.githubusercontent.com/16627589/81437244-76741c00-9130-11ea-964d-749e52ae2052.png)

**Comment by flipp33r** [comment]
Hi @cjthimm,

This is far from being a spam - just a friendly notice that you repository is hosting malware. You are free to verify on your own if information provided above is valid.
All other opened issues are for similar cases as yours.

Cheers,
Flipper

**Comment by StochasticTinkr** [comment]
@cjthimm, this is a legit problem: https://www.zdnet.com/article/github-warns-java-developers-of-new-malware-poisoning-netbeans-projects/

**Comment by cjthimm** [comment]
@StochasticTinkr I deleted the two files mentioned above and pushed those changes. This project hasn't been opened in netbeans by any of the contributors as far as I'm aware. Do you suggest I make any other changes?

**Comment by StochasticTinkr** [comment]
Honestly, I'm not an expert at all on the subject, just saw that article linked from Reddit.  I suggest you follow up though.

As far as never having been opened in netbeans, I'm very curious how the files got added to the project.

**Comment by cjthimm** [comment]
@StochasticTinkr ,this project is a clone of an existing GitHub project. Some class mates and I were building a genetic AI on top of it and we were using this as version control
